name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "A clear description of the feature you'd like to see"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: "Why would this feature be useful? What problem does it solve?"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: "Any alternative solutions or workarounds you've considered"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: "Any other context, mockups, or examples"
    validations:
      required: false
